### PR TITLE
sorta Refactorization

### PR DESCRIPTION
**Pull request by Akshat-sin-official**

### CODE REVIEW

**Comment by Akshat-sin-official** [comment]
could ya pls add "hacktoberfest-accepted" label @ this PR 😅

**Review by was07 — APPROVED** [review]

**Comment by was07** [comment]
> could ya pls add "hacktoberfest-accepted" label @ this PR 😅

What does "hacktoberfest-accepted" mean actually?

**Comment by Akshat-sin-official** [comment]
Ayo! read abt that here : https://hacktoberfest.com/

**Comment by Akshat-sin-official** [comment]
or add the hacktoberfest topic t the repo

**Pull request merged**
